image: docker:latest

services:
- docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" --build-arg=APP_VERSION=$CI_COMMIT_REF_NAME --build-arg=APP_COMMIT=$CI_COMMIT_SHA -f Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker tag "$CI_REGISTRY_IMAGE:latest" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  only:
    - tags

deploy:
  image: alpine
  stage: deploy
  variables:
    IMAGE_TAG: $CI_COMMIT_REF_NAME
  environment:
    name: production
    url: https://prefix.zazuko.com
  before_script:
    - wget -qO /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl
    - wget -qO /usr/local/bin/kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v2.0.3/kustomize_2.0.3_linux_amd64
    - chmod +x /usr/local/bin/kubectl /usr/local/bin/kustomize
  script:
    - cd k8s
    - kustomize edit set image registry.zazuko.com/docker/prefix-server=registry.zazuko.com/docker/prefix-server:$IMAGE_TAG
    - kubectl apply -k .
  only:
    - tags
    - triggers
    - web
