apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prefix-server

commonLabels:
  app.kubernetes.io/name: prefix-server

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - poddisruptionbudget.yaml

configMapGenerator:
  - name: varnish-config
    files:
      - ./default.vcl
