apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prefix-server
resources:
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: prefix-server

bases:
  - server
  - varnish
