apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish
spec:
  template:
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      volumes:
        - name: varnish-config-volume
          configMap:
            name: varnish-config
      containers:
      - name: prefix-server
        image: "docker.io/zazukoians/varnish:5.2.1"
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: varnish-config-volume
            mountPath: /etc/varnish/
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
