apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: varnish

resources:
  - deployment.yaml
  - service.yaml
  - poddisruptionbudget.yaml

configMapGenerator:
  - name: varnish-config
    files:
      - ./default.vcl
