apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - name: prefix-server
        image: prefix-server
        imagePullPolicy: IfNotPresent

        ports:
        - name: http
          containerPort: 3000
          protocol: TCP

        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: http

        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: http

        resources:
          requests:
            memory: "250Mi"
            cpu: "50m"
          limits:
            memory: "600Mi"
            cpu: "200m"
