apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2

  template:
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      containers:
        - name: prefix-server
          image: docker.io/zazuko/prefix-server
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http

          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http

          resources:
            requests:
              memory: "250Mi"
              cpu: "50m"

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            # This makes sure the pods are not all scheduled on the same node
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels: {}
                topologyKey: "kubernetes.io/hostname"
