/*
 * Data model of the API: generated by `npm run build-data` and served by `server/api/v1/*`.
 */

/** An RDF/JS term as serialized to JSON. */
export interface SerializedTerm {
  termType: string
  value: string
  language?: string
  datatype?: SerializedTerm
}

export interface SerializedQuad {
  subject: SerializedTerm
  predicate: SerializedTerm
  object: SerializedTerm
  graph: SerializedTerm
}

/** One triple of a term, with predicate and object shrunk to prefixed names when possible. */
export interface TermPart {
  /** prefixed predicate, or its full IRI when it cannot be shrunk */
  predicate: string
  predicateIRI?: string
  /** prefixed object IRI (or its full IRI when it cannot be shrunk), or the serialized literal / blank node */
  object: string | SerializedTerm
  objectIRI?: string
  quad: SerializedQuad
}

/** A searchable term (class, property, …) of a vocabulary. */
export interface TermEntry {
  iri: SerializedTerm
  prefixed: string
  graph: SerializedTerm
  parts: TermPart[]
  /** `schema` for `schema:Person` */
  prefixedSplitA: string
  /** `Person` for `schema:Person` */
  prefixedSplitB?: string
  /** `http://schema.org/` for `http://schema.org/Person` */
  iriSplitA: string
  iriSplitB?: string
  ontologyTitle: string
  label?: string
  /** text displayed in search results: the prefixed name and the label */
  itemText: string
}

export interface PrefixMetadata {
  namespace: string
  title: string
  description: string
}

export type PrefixTermSummary = Pick<TermEntry, 'itemText' | 'iri' | 'label' | 'prefixed'>

/** Terms of a vocabulary grouped by their prefixed `rdf:type`, plus the full IRIs of the other types. */
export interface PrefixEndpointData {
  otherTypes: string[]
  [prefixedType: string]: PrefixTermSummary[] | string[]
}

export interface SummaryEntry {
  prefix: string
  terms: number
}

/** prefix → term → prefixed `rdf:type`s */
export type PrefixComplete = Record<string, Record<string, string[]>>

export interface PrefixResponse {
  data: PrefixEndpointData
  metadata: PrefixMetadata
}

export type ConversionResponse = { success: true, value: string } | { success: false }

export interface HelpResponse {
  help: string
}

/** The files written by `npm run build-data` into `server/assets/datafiles/`. */
export interface DataFiles {
  searchArray: TermEntry[]
  searchArrayByPrefix: Record<string, TermEntry[]>
  prefixEndpointData: Record<string, PrefixEndpointData>
  prefixMetadata: Record<string, PrefixMetadata>
  summary: SummaryEntry[]
  prefixComplete: PrefixComplete
}
