import zlib from 'node:zlib'
import Fuse from 'fuse.js'
import type { DataFiles, PrefixComplete, PrefixEndpointData, PrefixMetadata, SummaryEntry, TermEntry } from '#shared/types/api'
import { fuseOptions } from './vocabularies'

export interface ApiData {
  fuse: Fuse<TermEntry>
  fuseByPrefix: Record<string, Fuse<TermEntry>>
  prefixEndpointData: Record<string, PrefixEndpointData>
  prefixMetadata: Record<string, PrefixMetadata>
  summary: SummaryEntry[]
  prefixComplete: PrefixComplete
}

type ServerAssets = ReturnType<typeof useStorage>

let dataPromise: Promise<ApiData> | null = null

async function readDataFile<T> (storage: ServerAssets, name: keyof DataFiles): Promise<T> {
  const raw = await storage.getItemRaw<Buffer | string>(`datafiles/${name}.json.gz`)
  if (!raw) {
    throw new Error(`Missing data file server/assets/datafiles/${name}.json.gz, run "npm run build-data" first`)
  }
  return JSON.parse(zlib.gunzipSync(raw).toString()) as T
}

async function loadData (): Promise<ApiData> {
  const storage = useStorage('assets:server')
  const [
    searchArray,
    searchArrayByPrefix,
    prefixEndpointData,
    prefixMetadata,
    summary,
    prefixComplete
  ] = await Promise.all([
    readDataFile<DataFiles['searchArray']>(storage, 'searchArray'),
    readDataFile<DataFiles['searchArrayByPrefix']>(storage, 'searchArrayByPrefix'),
    readDataFile<DataFiles['prefixEndpointData']>(storage, 'prefixEndpointData'),
    readDataFile<DataFiles['prefixMetadata']>(storage, 'prefixMetadata'),
    readDataFile<DataFiles['summary']>(storage, 'summary'),
    readDataFile<DataFiles['prefixComplete']>(storage, 'prefixComplete')
  ])

  return {
    fuse: new Fuse(searchArray, fuseOptions),
    fuseByPrefix: Object.fromEntries(
      Object.entries(searchArrayByPrefix).map(([prefix, items]) => [prefix, new Fuse(items, fuseOptions)])
    ),
    prefixEndpointData,
    prefixMetadata,
    summary,
    prefixComplete
  }
}

/**
 * The API data (generated by `npm run build-data` into `server/assets/datafiles`),
 * loaded and indexed once per process.
 */
export function getData (): Promise<ApiData> {
  if (!dataPromise) {
    dataPromise = loadData().catch((error) => {
      dataPromise = null
      throw error
    })
  }
  return dataPromise
}
