import zlib from 'node:zlib'
import Fuse from 'fuse.js'
import { fuseOptions } from './vocabularies.js'

const DATA_FILES = [
  'searchArray',
  'searchArrayByPrefix',
  'prefixEndpointData',
  'prefixMetadata',
  'summary',
  'prefixComplete'
]

let dataPromise = null

async function readDataFile (storage, name) {
  const raw = await storage.getItemRaw(`datafiles/${name}.json.gz`)
  if (!raw) {
    throw new Error(`Missing data file server/assets/datafiles/${name}.json.gz, run "npm run build-data" first`)
  }
  return JSON.parse(zlib.gunzipSync(raw).toString())
}

async function loadData () {
  const storage = useStorage('assets:server')
  const [
    searchArray,
    searchArrayByPrefix,
    prefixEndpointData,
    prefixMetadata,
    summary,
    prefixComplete
  ] = await Promise.all(DATA_FILES.map(name => readDataFile(storage, name)))

  return {
    fuse: new Fuse(searchArray, fuseOptions),
    fuseByPrefix: Object.fromEntries(
      Object.entries(searchArrayByPrefix).map(([prefix, items]) => [prefix, new Fuse(items, fuseOptions)])
    ),
    prefixEndpointData,
    prefixMetadata,
    summary,
    prefixComplete
  }
}

/**
 * The API data (generated by `npm run build-data` into `server/assets/datafiles`),
 * loaded and indexed once per process.
 */
export function getData () {
  if (!dataPromise) {
    dataPromise = loadData().catch((error) => {
      dataPromise = null
      throw error
    })
  }
  return dataPromise
}
