name: Test
on:
  push:
  pull_request:

jobs:
  test:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: |
          npm run build-data
          NODE_ENV=production npm run build:modern

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        env:
          NODE_ENV: production
        with:
          install: false
          start: npm start
          wait-on: "http://localhost:3000"
